version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: oro
      POSTGRES_PASSWORD: samri
      POSTGRES_DB: hirego
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oro"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://oro:samri@localhost:5432/hirego
      JWT_SECRET: your_jwt_secret
      NODE_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/uploads
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: